package com.wassimbeltaief.formforge.ksp.codegen

import com.squareup.kotlinpoet.ClassName
import com.squareup.kotlinpoet.CodeBlock
import com.squareup.kotlinpoet.FileSpec
import com.squareup.kotlinpoet.FunSpec
import com.squareup.kotlinpoet.KModifier
import com.squareup.kotlinpoet.MemberName
import com.squareup.kotlinpoet.ParameterSpec
import com.squareup.kotlinpoet.ParameterizedTypeName.Companion.parameterizedBy
import com.squareup.kotlinpoet.PropertySpec
import com.squareup.kotlinpoet.BOOLEAN
import com.squareup.kotlinpoet.STRING
import com.squareup.kotlinpoet.TypeSpec
import com.squareup.kotlinpoet.asClassName
import com.squareup.kotlinpoet.buildCodeBlock
import com.wassimbeltaief.formforge.ksp.parser.FieldModel
import com.wassimbeltaief.formforge.ksp.parser.FieldType
import com.wassimbeltaief.formforge.ksp.parser.SchemaModel
import com.wassimbeltaief.formforge.ksp.parser.ValidatorRule

// formforge-core types
private val fieldStateClass = ClassName("com.wassimbeltaief.formforge.core.state", "FieldState")
private val formStatusClass = ClassName("com.wassimbeltaief.formforge.core.state", "FormStatus")
private val formControllerClass = ClassName("com.wassimbeltaief.formforge.core", "FormController")

// built-in validators
private val notBlankValidatorClass = ClassName("com.wassimbeltaief.formforge.core.validation.builtin", "NotBlankValidator")
private val minLengthValidatorClass = ClassName("com.wassimbeltaief.formforge.core.validation.builtin", "MinLengthValidator")
private val mustBeTrueValidatorClass = ClassName("com.wassimbeltaief.formforge.core.validation.builtin", "MustBeTrueValidator")
private val validationResultClass = ClassName("com.wassimbeltaief.formforge.core.state", "ValidationResult")

// coroutines
private val mutableStateFlowClass = ClassName("kotlinx.coroutines.flow", "MutableStateFlow")
private val stateFlowClass = ClassName("kotlinx.coroutines.flow", "StateFlow")
private val updateFn = MemberName("kotlinx.coroutines.flow", "update")
private val asStateFlowFn = MemberName("kotlinx.coroutines.flow", "asStateFlow")

internal class FormStateGenerator {

    fun generate(schema: SchemaModel): FileSpec {
        val schemaClass = ClassName(schema.packageName, schema.schemaClassName)
        val holderClass = ClassName(schema.packageName, "${schema.schemaClassName}Controller")

        return FileSpec.builder(holderClass)
            .addFileComment("Generated by FormForge — do not edit")
            .addType(buildHolderClass(schema, schemaClass, holderClass))
            .build()
    }

    // -------------------------------------------------------------------------
    // *Holder class
    // Per-field: private _field MutableStateFlow + public field StateFlow
    // Form-level: status StateFlow, data property, validateAllSync, reset, clear, setFieldError
    // -------------------------------------------------------------------------

    private fun fieldStateType(field: FieldModel) = when (field.type) {
        FieldType.STRING -> fieldStateClass.parameterizedBy(STRING)
        FieldType.BOOLEAN -> fieldStateClass.parameterizedBy(BOOLEAN)
    }

    private fun buildHolderClass(
        schema: SchemaModel,
        schemaClass: ClassName,
        holderClass: ClassName,
    ): TypeSpec {
        val mutableStatusFlow = mutableStateFlowClass.parameterizedBy(formStatusClass)
        val publicStatusFlow = stateFlowClass.parameterizedBy(formStatusClass)

        return TypeSpec.classBuilder(holderClass)
            .addSuperinterface(formControllerClass.parameterizedBy(schemaClass))
            .primaryConstructor(buildConstructor(schemaClass))
            .addProperty(
                PropertySpec.builder("initial", schemaClass, KModifier.PRIVATE)
                    .initializer("initial")
                    .build()
            )
            // One private MutableStateFlow + one public StateFlow per field
            .apply {
                for (field in schema.fields) {
                    val stateType = fieldStateType(field)
                    val mutableFlowType = mutableStateFlowClass.parameterizedBy(stateType)
                    val publicFlowType = stateFlowClass.parameterizedBy(stateType)
                    addProperty(
                        PropertySpec.builder("_${field.name}", mutableFlowType, KModifier.PRIVATE)
                            .initializer(
                                "%T(%T(value = initial.%N, initialValue = initial.%N, label = %S, hint = %S))",
                                mutableStateFlowClass, fieldStateClass,
                                field.name, field.name, field.label, field.hint,
                            )
                            .build()
                    )
                    addProperty(
                        PropertySpec.builder(field.name, publicFlowType)
                            .initializer("_%N.%M()", field.name, asStateFlowFn)
                            .build()
                    )
                }
            }
            // status flow
            .addProperty(
                PropertySpec.builder("_status", mutableStatusFlow, KModifier.PRIVATE)
                    .initializer("%T(%T.Idle)", mutableStateFlowClass, formStatusClass)
                    .build()
            )
            .addProperty(
                PropertySpec.builder("status", publicStatusFlow, KModifier.OVERRIDE)
                    .initializer("_status.%M()", asStateFlowFn)
                    .build()
            )
            // data property
            .addProperty(buildDataProperty(schema, schemaClass))
            // per-field functions
            .apply {
                for (field in schema.fields) {
                    addFunction(buildUpdateFn(field))
                    addFunction(buildTouchFn(field))
                }
                addFunction(buildValidateAllSyncFn(schema))
                addFunction(buildResetFn(schema))
                addFunction(buildClearFn(schema))
                addFunction(buildSetFieldErrorFn(schema))
            }
            .build()
    }

    private fun buildConstructor(schemaClass: ClassName): FunSpec =
        FunSpec.constructorBuilder()
            .addParameter(
                ParameterSpec.builder("initial", schemaClass)
                    .defaultValue("%T()", schemaClass)
                    .build()
            )
            .build()

    private fun buildDataProperty(schema: SchemaModel, schemaClass: ClassName): PropertySpec {
        val getter = FunSpec.getterBuilder()
            .addCode(buildCodeBlock {
                add("return %T(", schemaClass)
                for ((index, field) in schema.fields.withIndex()) {
                    if (index > 0) add(", ")
                    add("%N = %N.value.value", field.name, "_${field.name}")
                }
                add(")\n")
            })
            .build()
        return PropertySpec.builder("data", schemaClass, KModifier.OVERRIDE)
            .getter(getter)
            .build()
    }

    // -------------------------------------------------------------------------
    // Per-field update / touch
    // -------------------------------------------------------------------------

    private fun buildUpdateFn(field: FieldModel): FunSpec {
        val syncValidators = field.validators.filterNot { it is ValidatorRule.Async }
        val paramType = if (field.type == FieldType.BOOLEAN) BOOLEAN else STRING
        return FunSpec.builder("update${field.name.capitalize()}")
            .addParameter("value", paramType)
            .addCode(buildCodeBlock {
                beginControlFlow("_%N.%M { s ->", field.name, updateFn)
                if (syncValidators.isEmpty()) {
                    addStatement("s.copy(value = value, isDirty = value != s.initialValue, errors = emptyList())")
                } else {
                    add("val errors = ")
                    add(runValidatorsExpr(syncValidators, "value"))
                    addStatement(".errorsOrEmpty()")
                    addStatement("s.copy(value = value, isDirty = value != s.initialValue, errors = errors)")
                }
                endControlFlow()
            })
            .build()
    }

    private fun buildTouchFn(field: FieldModel): FunSpec {
        val syncValidators = field.validators.filterNot { it is ValidatorRule.Async }
        return FunSpec.builder("touch${field.name.capitalize()}")
            .addCode(buildCodeBlock {
                beginControlFlow("_%N.%M { s ->", field.name, updateFn)
                if (syncValidators.isEmpty()) {
                    addStatement("s.copy(isTouched = true)")
                } else {
                    add("val errors = ")
                    add(runValidatorsExpr(syncValidators, "s.value"))
                    addStatement(".errorsOrEmpty()")
                    addStatement("s.copy(isTouched = true, errors = errors)")
                }
                endControlFlow()
            })
            .build()
    }

    // -------------------------------------------------------------------------
    // Form-level actions
    // -------------------------------------------------------------------------

    private fun buildValidateAllSyncFn(schema: SchemaModel): FunSpec {
        return FunSpec.builder("validateAllSync")
            .addModifiers(KModifier.OVERRIDE)
            .returns(Boolean::class.asClassName())
            .addCode(buildCodeBlock {
                addStatement("var allValid = true")
                for (field in schema.fields) {
                    val syncValidators = field.validators.filterNot { it is ValidatorRule.Async }
                    beginControlFlow("_%N.%M { s ->", field.name, updateFn)
                    add("val errors = (")
                    add(runValidatorsExpr(syncValidators, "s.value"))
                    addStatement(").errorsOrEmpty()")
                    addStatement("if (errors.isNotEmpty()) allValid = false")
                    addStatement("s.copy(isTouched = true, errors = errors)")
                    endControlFlow()
                }
                addStatement("return allValid")
            })
            .build()
    }

    private fun buildResetFn(schema: SchemaModel): FunSpec {
        return FunSpec.builder("reset")
            .addModifiers(KModifier.OVERRIDE)
            .addCode(buildCodeBlock {
                for (field in schema.fields) {
                    addStatement(
                        "_%N.value = %T(value = initial.%N, initialValue = initial.%N, label = %S, hint = %S)",
                        field.name, fieldStateClass, field.name, field.name, field.label, field.hint,
                    )
                }
            })
            .build()
    }

    private fun buildClearFn(schema: SchemaModel): FunSpec {
        return FunSpec.builder("clear")
            .addModifiers(KModifier.OVERRIDE)
            .addCode(buildCodeBlock {
                for (field in schema.fields) {
                    beginControlFlow("_%N.%M { s ->", field.name, updateFn)
                    when (field.type) {
                        FieldType.STRING -> addStatement("""s.copy(value = "", isDirty = "" != s.initialValue, errors = emptyList())""")
                        FieldType.BOOLEAN -> addStatement("s.copy(value = false, isDirty = false != s.initialValue, errors = emptyList())")
                    }
                    endControlFlow()
                }
            })
            .build()
    }

    private fun buildSetFieldErrorFn(schema: SchemaModel): FunSpec =
        FunSpec.builder("setFieldError")
            .addModifiers(KModifier.OVERRIDE)
            .addParameter("field", STRING)
            .addParameter("error", STRING)
            .addCode(buildCodeBlock {
                beginControlFlow("when (field)")
                for (field in schema.fields) {
                    beginControlFlow("%S ->", field.name)
                    beginControlFlow("_%N.%M { s ->", field.name, updateFn)
                    addStatement("s.copy(errors = listOf(error), isTouched = true)")
                    endControlFlow()
                    endControlFlow()
                }
                endControlFlow()
            })
            .build()

    // -------------------------------------------------------------------------
    // Validator chaining
    // -------------------------------------------------------------------------

    private fun runValidatorsExpr(validators: List<ValidatorRule>, valueExpr: String): CodeBlock {
        if (validators.isEmpty()) return buildCodeBlock { add("%T.Valid", validationResultClass) }
        return buildCodeBlock {
            add(validatorConstructor(validators.first()))
            add(".validate(%L)", valueExpr)
            for (v in validators.drop(1)) {
                add(".let { if (!it.isValid) it else ")
                add(validatorConstructor(v))
                add(".validate(%L) }", valueExpr)
            }
        }
    }

    private fun validatorConstructor(rule: ValidatorRule): CodeBlock = buildCodeBlock {
        when (rule) {
            is ValidatorRule.NotBlank -> add("%T(%S)", notBlankValidatorClass, rule.message)
            is ValidatorRule.MinLength -> add("%T(%L, %S)", minLengthValidatorClass, rule.min, rule.message)
            is ValidatorRule.MustBeTrue -> add("%T(%S)", mustBeTrueValidatorClass, rule.message)
            is ValidatorRule.Async -> error("Async validators are not inlined — handled by the Compose layer")
        }
    }
}
